---
# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Luis Cacho
baseurl: /
copyright: >-
  Made with ❤️ </br>
  Hosted on [GitHub](https://github.com/luiscachog/luiscachog.io) - Served by [Netlify](https://www.netlify.com) </br>
  &copy; 2014 - {year} - Luis Cacho

############################
## LANGUAGE
############################
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true


############################
## PAGE OPTIONS
############################
cascade:
  # Blog post options
  - _target:
      path: /post/**
    pager: true
    editable: true
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true
    share: true
    header:
      navbar:
        enable: false

############################
## MODULES
############################
module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
      disable: false
    - path: github.com/jakejarvis/hugo-mod-twemoji

############################
## ADVANCED
############################
enableGitInfo: true
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true

footnotereturnlinkcontents: <sup>^</sup>

permalinks:
  authors: '/author/:slug/'
  categories: '/category/:slug/'
  event: '/talk/:slug/'
  post: '/blog/:slug'
  publication_types: '/publication-type/:slug/'
  tags: '/tag/:slug/'

disableAliases: true

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - WebAppManifest
    - headers
    - redirects
  section:
    - HTML
    - RSS
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML
    - RSS

mediaTypes:
  application/manifest+json:
    suffixes:
      - webmanifest
outputFormats:
  WebAppManifest:
    mediaType: application/manifest+json
    rel: manifest

ignoreFiles:
  - \.ipynb$
  - .ipynb_checkpoints$
  - \.Rmd$
  - \.Rmarkdown$
  - _files$
  - _cache$

markup:
  _merge: deep
  # defaultMarkdownHandler: goldmark
  # goldmark:
  #   renderer:
  #     unsafe: true
  # highlight:
  #   codeFences: false
  # tableOfContents:
  #   startLevel: 2
  #   endLevel: 4

imaging:
  resampleFilter: lanczos
  quality: 90
  anchor: smart
timeout: 100000

taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: author

related:
  threshold: 80
  related_items: 3
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 80
    - name: author
      weight: 50
    - name: date
      weight: 10
      pattern: '2006'

services:
  rss:
    limit: 10
    site_feed: 'https://follow.it/luiscachog-io'

security:
  enableInlineShortcodes: false
  exec:
    allow:
      - ^dart-sass-embedded$
      - ^go$
      - ^npx$
      - ^postcss$
    osEnv:
      - (?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$
  funcs:
    getenv:
      - ^HUGO_
      - ^WC_
  http:
    methods:
      - (?i)GET|POST
    urls:
      - .*

sitemap:
  _merge: dee
