---
name: broken-link-checker
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  schedule:
    - cron: "00 10 * * 1"
  workflow_dispatch:

jobs:
  linkChecker:
    name: verify broken links
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.PERSONAL_SUBMODULES_PULL_KEY }}
          submodules: recursive
          lfs: true

      - name: restore lychee cache
        uses: actions/cache@v3
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: link checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --config .github/workflows/.lychee.toml './**/*.md' './**/*.html'
          fail: false
          jobSummary: true

      - name: create issue from file
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
